<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width">
    <title>Exception handling</title>
</head>
<body>
    <script>
        //Exception handling
        try
        {
           num=prompt("Enter a number");
           if(num==='')
           throw 'cannot be empty'
           if(isNaN(num))
           throw 'Enter a valid number'
           console.log(num*2)
        }
        catch(error)
        {
            console.log(error)
        }
        finally
        {
           console.log('bye');
        }
        //async,await
        async function fun()
        {
            return 'hello';
        }
        console.log(fun());

       let tosscoin=new Promise((resolve,reject)=>{
                let toss=false
                if(toss)
                setTimeout(resolve,3000,'gowtham is reached')
                else
                reject("gowtham is reached")
            })
         async function status()
         {
            try{
            console.log("Laptop")
            res=await tosscoin
            console.log(res)
            }
            catch(err)
            {
                console.log(err)
            }
         }

         //Json
         let details=
        [{
            "name":"gowthamraj",
            "roll no":138,
            "place":"salem",
            "course":"BE"
        }]
        console.log(details)
        console.log(JSON.parse(details))
    </script>
</body>
</html>